spring:
  application:
    name: hula-assistant
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8848

keenor:
  start-cron: 50 59 6 ? * 1,2,3
  end-cron: 0 1 7 ? * 1,2,3
