spring:
  application:
    name: hula-assistant
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zwh_vote?characterEncoding=utf-8&useSSL=false
    password: root
    username: root
server:
  port: 8848

keenor:
  order-date: 1553554830000
  start-cron: 50 59 6 ? * 2
  end-cron: 0 1 7 ? * 2

