spring:
  application:
    name: hula-assistant
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8848

keenor:
  order-date: 1553554830000
  start-cron: 50 59 6 ? * 2
  end-cron: 0 1 7 ? * 2
